### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Fernando_Mendes-180031864#1]
- Ser mais direto ao colocar os requisitos de solução.
- Sugere-se colocar todas as hipóteses de forma itemizada
- Melhorar o texto de metodologia

**Comment by fernandobvm** [comment]
README atualizado.

**Comment by fernandobvm** [comment]
Liberação para a continuidade recebida pelo Whatsapp.
