### ISSUE TITLE
Pré-Processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Fernando_Mendes-180031864#2]
- Não respondeu se a geometria está adequada!
- A frase: optou-se por trabalhar com uma malha estruturada por exigir menos memória computacional tem problemas conceituais e está muito contundente!
- Porque foi feita uma simulação com várias vazões? Não há justificativa para esta estratégia!
- A justificativa para afirmar que o escoamento é transicional está fraca!
- Há indicativos de que passos importantes do pré-processamento foram ignorados.
- Não há uma organização coerente no texto da descrição do pré-processamento.
- Muitas coisas colocadas no texto são parte do processamento.
- Esta parte deve ser totalmente refeita!

**Comment by fernandobvm** [comment]
README atualizado.

**Comment by lgnsparda** [comment]
- Pode seguir para a próxima etapa
