### ISSUE TITLE
Processamento e Pós-Processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Fernando_Mendes-180031864#3]
- Para o escopo deste projeto, não tem problema colocar curvas de convergência. No entanto, em projetos na indústria e academia, só se coloca se isto for estudado mais a fundo.
- Modificar a frase "Os resultados não estão de acordo com a realidade física do escoamento e nem com os dados mensurados pelo problema." para "Os resultados apresentados não estão de acordo com a teoria deste escoamento e nem com os dados mensurados pelo problema."
- O segundo parágrafo do item 4 deve ser movido para o fim deste item, após o estudo paramétrico.

**Comment by fernandobvm** [comment]
Readme atualizado

**Comment by lgnsparda** [comment]
- Corrigir erros localizados de digitação.
- Inserir as conclusões do projeto.
- DESAFIO: Após as conclusões, colocar o trabalho em formato de artigo científico

**Comment by fernandobvm** [comment]
Readme atualizado

**Comment by lgnsparda** [comment]
- Sugere-se fazer o artigo em um arquivo .md separado ou usando o overleaf.

**Comment by lgnsparda** [comment]
- Nao se observou o artigo científico

**Comment by lgnsparda** [comment]
- colocar o trabalho em formato de relatório técnico

**Comment by lgnsparda** [comment]
- Corrigir erros de digitação no relatório técnico
